### ISSUE TITLE
GitHub Projects

### ISSUE THREAD

**Issue by fa7ad** [Hedronium/pyloop#12]
I suggest the issues tagged `enhancement` be moved to [projects](https://github.com/Hedronium/pyloop/projects). These are things that do not break the program and thus I wouldn't call them issues. In projects, you can cake a board for a milestone and check off each enhancement before the release.

**Comment by omranjamal** [comment]
Woah! New Feature! Haven't logged in to github in a while.

**Comment by aniruddha-chakraborty** [comment]
Thank you for your suggestion! :+1:
