### ISSUE TITLE
Shutdown gracefully on interactive mode

### ISSUE THREAD

**Issue by omranjamal** [Hedronium/pyloop#6]
![huehue](http://i.imgur.com/hwaDxZu.jpg)

When I type a name in interactive mode for `pyloop get` command but cancel the command before pressing enter with `Ctrl+C` then a large stack trace can be seen which is intimidating and bad for UX.

**Comment by aniruddha-chakraborty** [comment]
This bug is fixed in 0.18 version . run "pip3 install pyloop --upgrade"
